// Generated by scripts/design-tokens.mjs from docs/design/tokens.json. Do not edit.

enum GeneratedColor {
  static let paper = DynamicColor(light: P3(0.9642, 0.9536, 0.9284), dark: P3(0.0958, 0.0865, 0.0724))
  static let paperRaised = DynamicColor(light: P3(0.9864, 0.9800, 0.9648), dark: P3(0.1267, 0.1160, 0.0997))
  static let field = DynamicColor(light: P3(1.0000, 1.0000, 1.0000), dark: P3(0.0584, 0.0506, 0.0387))
  static let ink = DynamicColor(light: P3(0.1239, 0.1111, 0.0916), dark: P3(0.9447, 0.9299, 0.8947))
  static let muted = DynamicColor(light: P3(0.4142, 0.3864, 0.3216), dark: P3(0.5980, 0.5705, 0.4953))
  static let categoryPinkText = DynamicColor(light: P3(0.6663, 0.1343, 0.2396), dark: P3(0.9216, 0.2934, 0.3874))
  static let categoryYellowText = DynamicColor(light: P3(0.4591, 0.3837, 0.0000), dark: P3(0.9733, 0.8459, 0.2883))
  static let categoryCyanText = DynamicColor(light: P3(0.1338, 0.4240, 0.5666), dark: P3(0.5054, 0.8140, 0.9841))
  static let categoryGreenText = DynamicColor(light: P3(0.1989, 0.4653, 0.2003), dark: P3(0.4074, 0.8085, 0.4049))
  static let categoryPurpleText = DynamicColor(light: P3(0.4940, 0.2144, 0.6777), dark: P3(0.6965, 0.3766, 0.9205))
  static let categoryTealText = DynamicColor(light: P3(0.1319, 0.4369, 0.5090), dark: P3(0.4173, 0.7741, 0.8662))
  static let categoryMintText = DynamicColor(light: P3(0.1748, 0.4437, 0.4378), dark: P3(0.5301, 0.8905, 0.8793))
  static let categoryBlueText = DynamicColor(light: P3(0.1216, 0.3677, 0.7494), dark: P3(0.2232, 0.5107, 0.9671))
  static let categoryIndigoText = DynamicColor(light: P3(0.3114, 0.3026, 0.7695), dark: P3(0.3658, 0.3610, 0.8697))
  static let categoryBrownText = DynamicColor(light: P3(0.4660, 0.3687, 0.2273), dark: P3(0.6558, 0.5612, 0.4264))
}
