// Generated by scripts/design-tokens.mjs from docs/design/tokens.json. Do not edit.

enum GeneratedColor {
  static let paper = DynamicColor(
    light: P3(0.9642, 0.9536, 0.9284),
    dark: P3(0.0958, 0.0865, 0.0724),
    increasedContrastLight: P3(0.9884, 0.9799, 0.9596),
    increasedContrastDark: P3(0.0677, 0.0588, 0.0452)
  )
  static let paperRaised = DynamicColor(
    light: P3(0.9864, 0.9800, 0.9648),
    dark: P3(0.1267, 0.1160, 0.0997),
    increasedContrastLight: P3(0.9975, 0.9932, 0.9831),
    increasedContrastDark: P3(0.0904, 0.0802, 0.0646)
  )
  static let field = DynamicColor(
    light: P3(1.0000, 1.0000, 1.0000),
    dark: P3(0.0584, 0.0506, 0.0387),
    increasedContrastLight: P3(1.0000, 1.0000, 1.0000),
    increasedContrastDark: P3(0.0270, 0.0215, 0.0145)
  )
  static let ink = DynamicColor(
    light: P3(0.1239, 0.1111, 0.0916),
    dark: P3(0.9434, 0.9286, 0.8935),
    increasedContrastLight: P3(0.1239, 0.1111, 0.0916),
    increasedContrastDark: P3(0.9434, 0.9286, 0.8935)
  )
  static let muted = DynamicColor(
    light: P3(0.3763, 0.3490, 0.2852),
    dark: P3(0.8497, 0.8205, 0.7404),
    increasedContrastLight: P3(0.3370, 0.3101, 0.2474),
    increasedContrastDark: P3(0.8960, 0.8666, 0.7856)
  )
  static let categoryPinkText = DynamicColor(
    light: P3(0.6377, 0.1159, 0.2238),
    dark: P3(0.9994, 0.7634, 0.7694),
    increasedContrastLight: P3(0.5851, 0.0224, 0.1818),
    increasedContrastDark: P3(0.9994, 0.8268, 0.8296)
  )
  static let categoryYellowText = DynamicColor(
    light: P3(0.4125, 0.3448, 0.0012),
    dark: P3(0.9719, 0.8446, 0.2868),
    increasedContrastLight: P3(0.3668, 0.3066, 0.0107),
    increasedContrastDark: P3(0.9877, 0.8602, 0.3052)
  )
  static let categoryCyanText = DynamicColor(
    light: P3(0.1060, 0.3722, 0.5016),
    dark: P3(0.5981, 0.8556, 1.0000),
    increasedContrastLight: P3(0.0116, 0.3302, 0.4631),
    increasedContrastDark: P3(0.7040, 0.8923, 0.9998)
  )
  static let categoryGreenText = DynamicColor(
    light: P3(0.1347, 0.3994, 0.1411),
    dark: P3(0.5068, 0.9105, 0.5001),
    increasedContrastLight: P3(0.0924, 0.3576, 0.1037),
    increasedContrastDark: P3(0.5502, 0.9556, 0.5421)
  )
  static let categoryPurpleText = DynamicColor(
    light: P3(0.4847, 0.2038, 0.6676),
    dark: P3(0.8958, 0.7740, 1.0000),
    increasedContrastLight: P3(0.4431, 0.1544, 0.6222),
    increasedContrastDark: P3(0.9211, 0.8333, 0.9983)
  )
  static let categoryTealText = DynamicColor(
    light: P3(0.0791, 0.3806, 0.4486),
    dark: P3(0.5157, 0.8730, 0.9666),
    increasedContrastLight: P3(0.0393, 0.3390, 0.4031),
    increasedContrastDark: P3(0.5918, 0.9148, 1.0000)
  )
  static let categoryMintText = DynamicColor(
    light: P3(0.1452, 0.3849, 0.3797),
    dark: P3(0.5288, 0.8892, 0.8780),
    increasedContrastLight: P3(0.1075, 0.3438, 0.3392),
    increasedContrastDark: P3(0.5672, 0.9284, 0.9168)
  )
  static let categoryBlueText = DynamicColor(
    light: P3(0.0750, 0.3288, 0.7079),
    dark: P3(0.7227, 0.8298, 0.9966),
    increasedContrastLight: P3(0.0045, 0.2826, 0.6592),
    increasedContrastDark: P3(0.7902, 0.8722, 0.9994)
  )
  static let categoryIndigoText = DynamicColor(
    light: P3(0.2931, 0.2801, 0.7460),
    dark: P3(0.7863, 0.8108, 1.0000),
    increasedContrastLight: P3(0.2575, 0.2344, 0.6992),
    increasedContrastDark: P3(0.8402, 0.8595, 0.9981)
  )
  static let categoryBrownText = DynamicColor(
    light: P3(0.4293, 0.3334, 0.1930),
    dark: P3(0.9019, 0.8077, 0.6742),
    increasedContrastLight: P3(0.3887, 0.2943, 0.1547),
    increasedContrastDark: P3(0.9539, 0.8524, 0.7085)
  )
}
