/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppLinkRouteImport } from './routes/_app/link'
import { Route as AppPlaylistsIndexRouteImport } from './routes/_app/playlists/index'
import { Route as AppPlaylistsIdRouteImport } from './routes/_app/playlists/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppLinkRoute = AppLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsIndexRoute = AppPlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsIdRoute = AppPlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof AppAdminRoute
  '/devices': typeof AppDevicesRoute
  '/link': typeof AppLinkRoute
  '/playlists/$id': typeof AppPlaylistsIdRoute
  '/playlists/': typeof AppPlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/admin': typeof AppAdminRoute
  '/devices': typeof AppDevicesRoute
  '/link': typeof AppLinkRoute
  '/': typeof AppIndexRoute
  '/playlists/$id': typeof AppPlaylistsIdRoute
  '/playlists': typeof AppPlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/link': typeof AppLinkRoute
  '/_app/': typeof AppIndexRoute
  '/_app/playlists/$id': typeof AppPlaylistsIdRoute
  '/_app/playlists/': typeof AppPlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/admin'
    | '/devices'
    | '/link'
    | '/playlists/$id'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/admin'
    | '/devices'
    | '/link'
    | '/'
    | '/playlists/$id'
    | '/playlists'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/admin'
    | '/_app/devices'
    | '/_app/link'
    | '/_app/'
    | '/_app/playlists/$id'
    | '/_app/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/link': {
      id: '/_app/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AppLinkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists/': {
      id: '/_app/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof AppPlaylistsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists/$id': {
      id: '/_app/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof AppPlaylistsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppLinkRoute: typeof AppLinkRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlaylistsIdRoute: typeof AppPlaylistsIdRoute
  AppPlaylistsIndexRoute: typeof AppPlaylistsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppLinkRoute: AppLinkRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlaylistsIdRoute: AppPlaylistsIdRoute,
  AppPlaylistsIndexRoute: AppPlaylistsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
