/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppLinkRouteImport } from './routes/_app/link'
import { Route as AppQueueRouteImport } from './routes/_app/queue'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppPeopleIdRouteImport } from './routes/_app/people/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppLinkRoute = AppLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/claim': typeof ClaimRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof AppAdminRoute
  '/devices': typeof AppDevicesRoute
  '/link': typeof AppLinkRoute
  '/queue': typeof AppQueueRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/people/': typeof AppPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/claim': typeof ClaimRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof AppAdminRoute
  '/devices': typeof AppDevicesRoute
  '/link': typeof AppLinkRoute
  '/queue': typeof AppQueueRoute
  '/': typeof AppIndexRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/people': typeof AppPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/claim': typeof ClaimRoute
  '/sign-in': typeof SignInRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/link': typeof AppLinkRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/': typeof AppIndexRoute
  '/_app/people/$id': typeof AppPeopleIdRoute
  '/_app/people/': typeof AppPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/sign-in'
    | '/admin'
    | '/devices'
    | '/link'
    | '/queue'
    | '/people/$id'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/claim'
    | '/sign-in'
    | '/admin'
    | '/devices'
    | '/link'
    | '/queue'
    | '/'
    | '/people/$id'
    | '/people'
  id:
    | '__root__'
    | '/_app'
    | '/claim'
    | '/sign-in'
    | '/_app/admin'
    | '/_app/devices'
    | '/_app/link'
    | '/_app/queue'
    | '/_app/'
    | '/_app/people/$id'
    | '/_app/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ClaimRoute: typeof ClaimRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/link': {
      id: '/_app/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AppLinkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppLinkRoute: typeof AppLinkRoute
  AppQueueRoute: typeof AppQueueRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppLinkRoute: AppLinkRoute,
  AppQueueRoute: AppQueueRoute,
  AppIndexRoute: AppIndexRoute,
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ClaimRoute: ClaimRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
