// Generates OrbisDesign/Tokens/GeneratedColors.swift and docs/design/tokens.css from
// docs/design/tokens.json, and validates the token source against its schema.
//
// Usage:
//   node scripts/design-tokens.mjs           write the generated files
//   node scripts/design-tokens.mjs --check   fail when a generated file is stale
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";

export const root = fileURLToPath(new URL("../", import.meta.url));
export const sourcePath = path.join(root, "docs/design/tokens.json");
export const schemaPath = path.join(root, "docs/design/tokens.schema.json");
export const swiftPath = path.join(
  root,
  "apps/apple/OrbisDesign/Sources/OrbisDesign/Tokens/GeneratedColors.swift"
);
export const cssPath = path.join(root, "docs/design/tokens.css");

const parseOklch = (text) => {
  const match =
    /oklch\(\s*(?<l>[\d.]+)\s+(?<c>[\d.]+)\s+(?<h>[\d.]+)\s*\)/u.exec(text);
  if (!match) {
    throw new Error(`Not an oklch() color: ${text}`);
  }
  return {
    c: Number(match.groups.c),
    h: Number(match.groups.h),
    l: Number(match.groups.l),
  };
};

const oklchToLinearSrgb = ({ l, c, h }) => {
  const a = c * Math.cos((h * Math.PI) / 180);
  const b = c * Math.sin((h * Math.PI) / 180);
  const l_ = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m_ = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s_ = (l - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_,
    -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_,
    -0.0041960863 * l_ - 0.7034186147 * m_ + 1.707614701 * s_,
  ];
};

// Linear sRGB → linear Display P3 (via XYZ D65).
const linearSrgbToLinearP3 = ([r, g, b]) => {
  const x = 0.4123908 * r + 0.35758434 * g + 0.18048079 * b;
  const y = 0.21263901 * r + 0.71516868 * g + 0.07219232 * b;
  const z = 0.01933082 * r + 0.11919478 * g + 0.95053215 * b;
  return [
    2.4934969 * x - 0.9313836 * y - 0.4027108 * z,
    -0.8294889 * x + 1.7626641 * y + 0.0236247 * z,
    0.0358458 * x - 0.0761724 * y + 0.9568845 * z,
  ];
};

const gamma = (v) =>
  v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055;
const clamp = (v) => Math.min(1, Math.max(0, v));
const channel = (v) => clamp(gamma(v)).toFixed(4);

const p3 = (oklch) =>
  linearSrgbToLinearP3(oklchToLinearSrgb(parseOklch(oklch))).map(channel);

const swiftName = (text) =>
  text.replaceAll(/-(?<letter>[a-z])/gu, (_, letter) => letter.toUpperCase());

/// Both generated files, as the text they should hold. Pure, so `--check` and a write
/// cannot disagree about what the token source means.
export const render = (tokens) => {
  const swiftLines = [
    "// Generated by scripts/design-tokens.mjs from docs/design/tokens.json. Do not edit.",
    "",
    "enum GeneratedColor {",
  ];
  const cssLines = [
    ":root {",
    "  /* generated from docs/design/tokens.json */",
  ];

  const emit = (name, { light, dark }) => {
    const l = p3(light);
    const d = p3(dark);
    swiftLines.push(
      `  static let ${name} = DynamicColor(light: P3(${l.join(", ")}), dark: P3(${d.join(", ")}))`
    );
    cssLines.push(`  --orbis-${name}: light-dark(${light}, ${dark});`);
  };

  for (const [name, value] of Object.entries(tokens.color)) {
    if (name === "categoryText") {
      for (const [category, shades] of Object.entries(value)) {
        const setName = `category-${category}-text`;
        emit(swiftName(setName), shades);
      }
    } else {
      emit(name, value);
    }
  }
  for (const [name, value] of Object.entries(tokens.radius)) {
    cssLines.push(`  --orbis-radius-${name}: ${value}px;`);
  }
  cssLines.push("}");
  swiftLines.push("}");

  return {
    css: `${cssLines.join("\n")}\n`,
    swift: `${swiftLines.join("\n")}\n`,
  };
};

/// Throws when the token source does not match its schema. The declared `$schema` must
/// resolve to the schema in this repo; a dangling path fails rather than being ignored.
export const validate = (tokens) => {
  const ajv = new Ajv2020({ allErrors: true });
  const check = ajv.compile(JSON.parse(readFileSync(schemaPath, "utf-8")));
  if (!check(tokens)) {
    throw new Error(
      `docs/design/tokens.json does not match its schema:\n${ajv.errorsText(check.errors, { separator: "\n" })}`
    );
  }
  const declaredPath = path.resolve(path.dirname(sourcePath), tokens.$schema);
  if (declaredPath !== schemaPath) {
    throw new Error(
      `docs/design/tokens.json points its $schema at ${tokens.$schema}, which is not docs/design/tokens.schema.json.`
    );
  }
};

export const loadTokens = () => JSON.parse(readFileSync(sourcePath, "utf-8"));

const readIfPresent = (file) => {
  try {
    return readFileSync(file, "utf-8");
  } catch (error) {
    if (error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
};

/// Names the generated files that differ from the token source, or an empty list.
export const staleFiles = (rendered) => {
  const stale = [];
  if (readIfPresent(swiftPath) !== rendered.swift) {
    stale.push(swiftPath);
  }
  if (readIfPresent(cssPath) !== rendered.css) {
    stale.push(cssPath);
  }
  return stale;
};

const relative = (file) => path.relative(root, file);

export const main = (argv = process.argv.slice(2)) => {
  const tokens = loadTokens();
  validate(tokens);
  const rendered = render(tokens);
  const check = argv.includes("--check");

  if (!check) {
    writeFileSync(swiftPath, rendered.swift);
    writeFileSync(cssPath, rendered.css);
    console.log(`wrote ${relative(swiftPath)} and ${relative(cssPath)}`);
    return 0;
  }

  const stale = staleFiles(rendered);
  if (stale.length > 0) {
    console.error(
      `Design tokens are stale:\n${stale.map((file) => `  ${relative(file)}`).join("\n")}\nRun \`bun run tokens:generate\` and commit the result.`
    );
    return 1;
  }
  console.log("design tokens are up to date");
  return 0;
};

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = main();
}
